blueprint:
  name: No Motion Light Off
  description: Turn off a light when motion is not detected anymore.
  domain: automation
  source_url: https://github.com/DanTheMinotaur/rand/blob/main/homeassistant/automations/no_motion_light.yaml
  author: DanTheMinotaur
  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    light_target:
      name: Light 
      selector:
        target:
          entity:
            domain: light
    no_motion_wait:
      name: No Motion Time
      description: Amount of seconds no motion is detected before turning off the light
      default: 600
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

mode: restart
max_exceeded: info

trigger:
  platform: state
  entity_id: !input motion_entity
  from: "on"
  to: "off"
  for:
    seconds: !input no_motion_wait
action:
  - service: light.turn_off
    target: !input light_target
