blueprint:
  name: Rainbow Lights
  description: >-
    Script to cycle an RGB light with different colours.
  domain: script
  source_url: https://github.com/DanTheMinotaur/rand/blob/main/homeassistant/script/rainbow_light.yaml
  author: DanTheMinotaur
  input:
    light_target:
      name: Light Entity
      description: The device to cycle colours
      selector:
        target:
          entity:
            domain: light
    light_transistion:
      name: Light Transistion
      description: Set the light colour transistion time
      selector:
        number:
          min: 1
          max: 200
          unit_of_measurement: seconds
          mode: slider
      default: 10
    delay:
      name: Transistion Delay
      description: How long the light stays the same colour(seconds)
      selector:
        number:
          min: 1
          max: 200
          unit_of_measurement: seconds
          mode: slider
      default: 10
    num_cycles:
      name: Colour Cycles Before Exit
      description: Number of times script will cycle through colours before exit(negative number = no exit)
      selector:
        number:
          min: -1
          max: 1000000
          unit_of_measurement: cycles
          mode: slider
      default: -1

mode: single
sequence:
  - repeat:
      sequence:
        - service: light.turn_on
          data:
            xy_color: |
              {{  colors[(now().second/2.5)|round(0)] }}
            transition: !input light_transistion
          target: !input light_target
        - delay:
            seconds: !input delay
      while:
        - condition: template
          value_template: "{{ repeat.index != num_cycles }}"
variables:
  num_cycles: !input num_cycles
  colors: |-
    {{ [[0.217,0.077], [0.157,0.05], [0.136,0.04], [0.137,0.065],
        [0.141,0.137], [0.146,0.238], [0.151,0.343], [0.157,0.457],
        [0.164,0.591], [0.17,0.703], [0.172,0.747], [0.199,0.724],
        [0.269,0.665], [0.36,0.588], [0.444,0.517], [0.527,0.447],
        [0.612,0.374], [0.677,0.319], [0.701,0.299], [0.667,0.284],
        [0.581,0.245], [0.477,0.196], [0.385,0.155], [0.301,0.116],
        [0.217,0.077]] }}
  